# Generated by Django 4.2 on 2025-10-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_license'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='third_party',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='third_party',
        ),
        migrations.AddField(
            model_name='account',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.account'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='temp-number', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.account')),
                ('third_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.thirdparty')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-debit', 'account__code'],
            },
        ),
    ]
