# Generated by Django 4.2 on 2025-10-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_account_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AddField(
            model_name='account',
            name='tipo',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('ORDEN_DEUDOR', 'Orden Deudor'), ('ORDEN_ACREEDOR', 'Orden Acreedor')], default='ACTIVO', max_length=20),
        ),
    ]
