# Generated by Django 4.2 on 2025-11-02 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_account_options_account_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_party_nit', models.CharField(db_index=True, max_length=20)),
                ('third_party_name', models.CharField(blank=True, max_length=200)),
                ('confidence_score', models.IntegerField(default=1, help_text='Cuántas veces se ha confirmado esta regla')),
                ('last_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('average_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_by_user', models.BooleanField(default=False, help_text='True si la creó el usuario, False si la aprendió el sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_rules', to='transactions.company')),
            ],
            options={
                'verbose_name': 'Regla de Clasificación',
                'verbose_name_plural': 'Reglas de Clasificación',
                'ordering': ['-confidence_score', '-updated_at'],
                'unique_together': {('company', 'third_party_nit')},
            },
        ),
    ]
