# Generated by Django 4.2 on 2025-11-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_accountingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='transaction_prefix',
            field=models.CharField(default='TRX', help_text='Prefijo para números de comprobante (ej: TRX, CRTJ)', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
